namespace Game.Statistics
{
    public enum StatisticIdentifiant
    {
        Damage,
        DamagePercentage,
        DamagePercentageAgainstWeak,
        Health,
        MaxHealth,
        MaxHealthFlat,
        MaxHealthPercentage,
        Defense,
        DefenseFlat,
        Cooldown,
        Duration,
        BuffDuration,
        Range,
        Reach,
        Leach,
        AttackSpeed,
        AttackSpeedPercentage,
        AttackPower,
        AttackPowerPercentage,
        Speed,
        SpeedPercentage,
        Heal,
        DefensePercentage,
        ArmorPenetration,
        DamageMultiplier,
        DamageTakenPercentage,
    }
}